### ISSUE TITLE
Whether to specify all version number in Dockerfile?

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#11]
Consulted @ttimbers that we should specify the version number of all packages in Dockerfile/environment.yml
For doing this, we can run the container -> `conda list` to list the packages and version number in the container -> copy and edit our Dockerfile/environment.yml -> rebuild Docker image

**Comment by ttimbers** [comment]
Yes, that sounds like a great plan!

**Comment by Jing-19** [comment]
Updated! Package versions have been added to Dockerfile and environment.yaml, and its on main branch now!
