### ISSUE TITLE
Updating README.md file

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#12]
@WeilinHan8 will work on updating README.md file with docker and test instructions

**Comment by WeilinHan8** [comment]
Also need to update the report with pdf.

**Comment by Jing-19** [comment]
Please also update the package versions in README!

**Comment by Jing-19** [comment]
Added developer notes/docker/tests to README, please review and modify as needed. pdf link needs to be done.

**Comment by WeilinHan8** [comment]
updated report link
