### ISSUE TITLE
Pytest Issue

### ISSUE THREAD

**Issue by Aishwarya120111** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#15]
Hi all,

I have created my function file and pytest file. I am getting below error when trying to run my test.
In my environment I have pandas installed, but it is still not able to find out the module.
<img width="696" alt="pytest" src="https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/assets/80033106/7ab76ac8-6f9d-4790-9b05-7685d1d82d15">

**Comment by tonyshumlh** [comment]
May I know if you are running it in local IDE or local Notebook or Docker Notebook?

**Comment by Aishwarya120111** [comment]
I am running in my local notebook with 522 kernel

**Comment by tonyshumlh** [comment]
Narrowed down this problem that it seems relating to the difference between Windows and Linux/Mac as it works well in Linux container

**Comment by Aishwarya120111** [comment]
Confirmed from Tiffany, that it is fine as its working in the linux container.
