### ISSUE TITLE
Incorporate Functions into Analysis Notebook

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#20]
Hi @Aishwarya120111 @Jing-19 @WeilinHan8 
Great if you can post here which part of the codes in the current Analysis Notebook are to be replaced by your functions (with screenshot if needed). Thanks

**Comment by Jing-19** [comment]
EDA session for scatter plots: chart_1, chart_2, chart_3, chart_4. (located right before EDA conclusion)

**Comment by Aishwarya120111** [comment]
Kindly replace the below code cells with the function for scoring metrics.
Below is the function "scoring_metrics(random_search,X_train,y_train,X_test,y_test)"
<img width="459" alt="image" src="https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/assets/80033106/f02213c6-c6e8-4221-8198-2ff90db291d7">

**Comment by tonyshumlh** [comment]
Hi @Jing-19 @WeilinHan8 @Aishwarya120111 The merge is done. Feel free to review and comment. Thanks :)
