### ISSUE TITLE
Abstract more code from your literate code document

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#25]
Hey team,
please finish this task as we discussed:
Data import and wrangling -  @WeilinHan8 
Input - all separate raw data.csv 
Output - save_the_earth_processed_data.csv (further data type clean up included)
EDA -  @Jing-19 
Input save_the_earth_processed_data.csv
Output - train_df.csv and test_df.csv
Model -  @tonyshumlh 
Input: train_df.csv
Output: trained_model/pipeline, scaled_train_data, model_selection result, hyperparameter result
Model -  @Aishwarya120111 
Input : Train data, test data, model result
Output : score tables, plots

**Comment by tonyshumlh** [comment]
Hi @WeilinHan8 
please find my part in the PR https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/pull/32
thank you

**Comment by Aishwarya120111** [comment]
@tonyshumlh @Jing-19 @WeilinHan8 
I have created script for evaluation script. I am saving my tables and figures under result folder. Kindly review the PR #35

**Comment by Jing-19** [comment]
Hi team, I have finished the EDA part, please find the PR #34 !

**Comment by tonyshumlh** [comment]
Hi team, I have finished my part, please find the PR https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/pull/47
