### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#29]
@WeilinHan8 will Update README.md

**Comment by Jing-19** [comment]
# split data into train and test sets
python scripts/split.py \
   --raw_data=Data/Processed/save_the_earth_processed_data.csv \
   --data_to=Data/Processed

# perform eda and save plots
python scripts/eda.py \
   --train_df=Data/Processed/train_df.csv
   --plot_to=results/figures

**Comment by WeilinHan8** [comment]
python scripts/data_fetch_clean.py --write-to=results/tables

**Comment by Aishwarya120111** [comment]
Perform Evaluate scripts and results

python scripts/evaluate-save-on-earth.py --train_data=Data/Processed/train_df.csv --test_data=Data/Processed/test_df.csv --pipeline_from=results/models/co2_pipeline.pickle --results_to=results --seed=123

**Comment by WeilinHan8** [comment]
Updated!
