### ISSUE TITLE
Write scipt for render to create a html + remove notebook cell input

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#30]
Hey @tonyshumlh 
Please write a script to automate  creating HTML Thanks!

**Comment by tonyshumlh** [comment]
Dockerfile is updated for the package jupyter-book

**Comment by tonyshumlh** [comment]
Need to add .nojekyll file for Github Page

**Comment by Jing-19** [comment]
@WeilinHan8 linked the updated html report to README; update the summary in README (maybe change the reference as well)

**Comment by tonyshumlh** [comment]
Updated in https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/pull/47

**Comment by WeilinHan8** [comment]
Great, thank you Tony!
