### ISSUE TITLE
Peer Review 3: Docstring for functions

### ISSUE THREAD

**Issue by Aishwarya120111** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#55]
Maybe the docstring of the functions in scripts can be more detailed, in particular maybe include which datatype of the parameters should be provided to the functions.

@tonyshumlh preprocess_and_estimator.py
@WeilinHan8 data_fetch_clean.py
@Jing-19 split.py, eda.py
@Aishwarya120111 evaluate-save-on-earth.py

**Comment by tonyshumlh** [comment]
Done for my script

**Comment by Aishwarya120111** [comment]
I have added docstring for my script and raised the pr https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/pull/64

**Comment by WeilinHan8** [comment]
I have added docstring for my scirpt, you can check it in #63

**Comment by Aishwarya120111** [comment]
Docstrings updated for all the scripts
