### ISSUE TITLE
Change the folder names in ReadMe

### ISSUE THREAD

**Issue by Aishwarya120111** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#58]
Change the folder names in Running analysis in readme.
<img width="438" alt="image" src="https://github.com/UBC-MDS/DSCI_522_Group-11_Save-The-Earth/assets/80033106/b285729a-32b1-4df3-94a7-f7b581a06fe7">

**Comment by tonyshumlh** [comment]
Done
